services:
  hadoop-master:
    container_name: hadoop-master
    restart: always
    build: ./hadoop/master
    ports:
      - 9870:9870
      - 9000:9000
    # networks:
    #  - bds-network
    volumes:
      - hadoop_master:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop/hadoop.env

  hadoop-hadoop_slave1:
    container_name: hadoop-hadoop_slave1
    restart: always
    build: ./hadoop/hadoop_slave1
    volumes:
      - hadoop_hadoop_slave1:/hadoop/dfs/data
    # networks:
    #  - bds-network
    environment:
      SERVICE_PRECONDITION: "hadoop-master:9870"
    env_file:
      - ./hadoop/hadoop.env